iname: CI/CD Frontend DEV

on:
  push:
    branches:
      - develop
    paths:
      - 'CODE/frontend/**'   # seulement si le frontend change

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Déployer Frontend sur VPS DEV
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 28796
          script: |
            cd ~/IMTECH
            ./deploy_dev.sh